FROM node:13.13.0-alpine AS compile-image

WORKDIR /app
COPY ./Frontend .

ENV PATH /app/node_modules/.bin:$PATH

RUN npm install
RUN ng build --prod

FROM nginx:1.17-alpine

RUN rm -rf /usr/share/nginx/html/*
COPY --from=compile-image  /app/dist /usr/share/nginx/html

EXPOSE 80